In [1]:
import os
import pandas as pd

In [3]:
path = "./foster-care-data-science"

all_years_data = pd.read_csv("Children_in_Foster_Care_Annually___Beginning_1994.csv")
all_years_data.head()

,County,Year,Adoptive Home,Agency Operated Boarding Home,Approved Relative Home,Foster Boarding Home,Group Home,Group Residence,Institution,Supervised Independent Living,Other,Total Days In Care,Admissions,Discharges,Children In Care,Number of Children Served,Indicated CPS Reports
0,ALBANY,2020,0,1927,9793,51742,6211,2890,10529,764,672,84528,126,92,237,341,612.0
1,ALLEGANY,2020,0,117,6573,7831,177,0,3347,177,1098,19320,13,26,45,70,107.0
2,BROOME,2020,0,0,12965,69542,6097,149,8324,4765,345,102187,119,106,294,399,962.0
3,CATTARAUGUS,2020,0,397,6776,9325,0,621,2164,177,41,19501,23,38,51,81,227.0
4,CAYUGA,2020,0,0,2777,21547,918,0,3903,0,0,29145,44,32,86,118,215.0